### ISSUE TITLE
add nonce to grammar urls

### ISSUE THREAD

**Issue by balmas** [alpheios-project/res-client#2]
as reported in alpheios-project/webextension#105, Firefox won't observe an anchor change in an iframe source url as a new url, and so it doesn't scroll the frame to a new target. A workaround for this is is to add a querystring nonce to the url

**Comment by balmas** [comment]
Ready for testing in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-5

**Comment by monzug** [comment]
looks good
